edge:
  # DNS name edge clients and other routers will use to reach this router
  advertisedHost:  # router1.zitik8s
  # TCP port to pair with advertisedHost
  advertisedPort: 443
  service:
    enabled: true
    type: ClusterIP
  traefikTcpRoute:
    enabled: true
    entryPoints:
      - websecure

linkListeners:
  transport:
    # enabled by default; miniziti may disable/override this listener
    service:
      enabled: true
      type: ClusterIP
    traefikTcpRoute:
      enabled: true
      entryPoints:
        - websecure
