apiVersion: v1
entries:
  traefik:
  - apiVersion: v2
    appVersion: 1.1.9
    created: "2022-01-07T15:41:47.820288-05:00"
    description: A Traefik based Kubernetes ingress controller
    digest: d0dcf1f7eea2b423841e5a91cbcb7007207dde14ca1b5debc07f8a55c6bdce45
    home: https://traefik.io/
    icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
    keywords:
    - traefik
    - ingress
    type: application
    urls:
    - traefikz-0.0.1.tgz
    version: 0.0.1
generated: "2022-01-07T15:41:47.818063-05:00"
