apiVersion: v3
appVersion: 0.29.0
dependencies:
- condition: cert-manager.enabled
  name: cert-manager
  repository: https://charts.jetstack.io
  version: ~1.11.0
- condition: trust-manager.enabled
  name: trust-manager
  repository: https://charts.jetstack.io
  version: ~0.4.0
- condition: ingress-nginx.enabled
  name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx/
  version: ~4.5.2
description: Host an OpenZiti controller in Kubernetes
name: ziti-controller
type: application
version: 0.5.0
