apiVersion: v2
appVersion: 1.1.3
description: Dial OpenZiti services with a tunneler daemonset
kubeVersion: '>= 1.20.0-0'
name: ziti-edge-tunnel
type: application
version: 1.0.0
icon: https://openziti.io/img/ziti-logo-dark.svg
home: https://openziti.io
sources:
- https://github.com/openziti/ziti-tunnel-sdk-c
keywords:
- openziti
- coredns
- node-local-dns
