# Default values for ziti-edge-tunnel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  registry: docker.io
  repository: openziti/ziti-edge-tunnel
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  args: []  # list(string): additional args passed to the container command
  command: []  # list(string): override entrypoint command (optional)

migrateJobImage:
  registry: docker.io
  repository: portainer/kubectl-shell
  pullPolicy: IfNotPresent
  tag: ""

# -- JSON of an enrolled identity to write in the PVC
zitiIdentity: ""
# -- JWT to enroll a new identity and write in the PVC
zitiEnrollToken: ""

dnsPolicy: ClusterFirstWithHostNet

secret: {}
  # existingSecretName: ""  # string: Use an existing secret name (if set, disables PVC)
  # keyName: persisted-identity  # string: key in the secret (default: persisted-identity)

imagePullSecrets: []  # list(string)
nameOverride: ""  # string
fullnameOverride: ""  # string

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name: ""

# Configures the liveness probe for the tunnel pod
livenessProbe:
  exec:
    command:
      - /bin/bash
      - -c
      - if (ziti-edge-tunnel tunnel_status | jq '.Success'); then true; else false; fi
  failureThreshold: 3
  initialDelaySeconds: 180
  periodSeconds: 60
  successThreshold: 1
  timeoutSeconds: 10

log:
  # -- Ziti log level, from 0 to 6 (see README.md Reference)
  zitiLevel: 3
  # -- TLSUV log level, from 0 to 6 (see README.md Reference)
  tlsUVLevel: 3
  # -- Set log time format, if set to "utc", then in UTC format, otherwise in milliseconds since the program has started.
  timeFormat: utc

podAnnotations: {}  # object
podSecurityContext: {}  # object
hostNetwork: true  # bool
securityContext:
  privileged: true

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

ports: []

# -- constrain worker nodes where the ziti-edge-tunnel pod can be scheduled
nodeSelector: {}
  #  node-role.kubernetes.io/node: worker

tolerations: []
  # - key: node-role.kubernetes.io/master
  #   operator: Exists
  #   effect: NoSchedule

affinity: {}

systemDBus:
  # -- enable D-Bus socket connection
  enabled: true
  # -- file path of the System D-Bus socket mount
  systemDBusSocketMnt: /var/run/dbus/system_bus_socket

spireAgent:
  # -- if you are running a container with the spire-agent binary installed
  # then this will allow you to add the hostpath necessary for connecting to
  # the spire socket
  enabled: false
  # -- file path of the spire socket mount
  spireSocketMnt: /run/spire/sockets

# -- additional volumes to mount to ziti-edge-tunnel container
additionalVolumes: []
#  - name: additional-volume-1
#    volumeType: secret
#    mountPath: /path/to/mount/1
#    secretName: name-of-secret
