apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ziti-host.fullname" . }}-identity-migrate
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: default
      initContainers:
        - name: chown-identity-dir
          image: busybox
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "-c", "chown -R {{ .Values.podSecurityContext.runAsUser }}:{{ .Values.podSecurityContext.runAsGroup }} {{ include "ziti-host.identityMountPath" . }}"]
          volumeMounts:
            - name: identity-pvc
              mountPath: {{ include "ziti-host.identityMountPath" . }}
      containers:
        - name: migrate-identity
          image: portainer/kubectl-shell
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash", "/scripts/migrate.sh"]
          securityContext:
            runAsUser: {{ .Values.podSecurityContext.runAsUser }}
            runAsGroup: {{ .Values.podSecurityContext.runAsGroup }}
          volumeMounts:
            - name: identity-pvc
              mountPath: {{ include "ziti-host.identityMountPath" . }}
            - name: migrate-script
              mountPath: /scripts
      volumes:
        - name: identity-pvc
          persistentVolumeClaim:
            claimName: {{ include "ziti-host.fullname" . }}-identity-pvc
        - name: migrate-script
          configMap:
            name: {{ include "ziti-host.fullname" . }}-identity-migrate
            defaultMode: 0755
