{{if not .Values.omitIdentityMigration}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ziti-router.fullname" . }}-hook-serviceaccount
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-8"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ziti-router.fullname" . }}-hook-role
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-7"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ziti-router.fullname" . }}-hook-rolebinding
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ziti-router.fullname" . }}-hook-role
subjects:
  - kind: ServiceAccount
    name: {{ include "ziti-router.fullname" . }}-hook-serviceaccount
    namespace: {{ .Release.Namespace }}
{{end}}